### ISSUE TITLE
tiresias seeing files that are no longer there

### ISSUE THREAD

**Issue by dovi5988** [pchero/asterisk-tiresias#7]
Hi,

I have in /etc/asterisk/tiresias.conf
`[global]`
`tolerance=0.001`

`[jack]`
`directory=/tmp/jack`

Yet there are no files in /tmp/jack (there used to be but they have since been deleted)
`root@fingerprint1:/etc/asterisk# ll /tmp/jack/`
`total 68`
`drwxr-xr-x  2 root root  4096 Jul 30 11:16 ./`
`drwxrwxrwt 12 root root 61440 Jul 30 11:21 ../`
`root@fingerprint1:/etc/asterisk# `

Yet tiresias seems to think the files still exist:

`root@fingerprint1:/etc/asterisk# asterisk -rx' tiresias show audios jack'`
`Uuid                                 Name                                          Context                              Hash                              `
`61e06fa8-e017-458b-94f5-5a092feb2fda beep_sound3.wav                               jack                                 8bb58ed9e304fa2b35a6d545ad46315d    `
`8a98cfd6-9713-4ba2-a0be-80ec4b2ee28b intro2.wav                                    jack                                 a275a15b3822109ca9289cd7018a82fa    `
`9c22c644-45a8-4f3a-b25d-54d1ee5c4db4 AAAAAA_example.wav                            jack                                 a87c1281010354a8bddd3ff52e008211    `
`b9024791-ccb2-49fd-bbce-8e016e122f8c AAAAAAA.wav                                   jack                                 6265d3bdb7aea3540bae8d32bd1a8a70 `   
`b16c861f-d135-447e-ad05-40040ef3fcb9 TO_CALL_CENTER_d7517f9f60793172a384ad0a350857 jack                                 a6829ceefa2ba299d179b84fb2c68f51    `
`root@fingerprint1:/etc/asterisk# `

**Comment by pchero** [comment]
Hi dovi5988,

That's the bug. I fill fix it asap. :)

**Comment by pchero** [comment]
Fixed it.
